### ISSUE TITLE
Make the theme printable

### ISSUE THREAD

**Issue by AlexisTM** [mudassir0909/jsonresume-theme-elegant#99]
By adding ` page-break-inside: avoid;` to the `card-nested` CSS, the theme becomes printable with nice transitions.

```css
  .card-nested {
    min-height: 0;
    border-width: 1px 0 0 0;
    page-break-inside: avoid;
  }
```

By adding the following CSS, the border of the background is not visible while printing.

```css
  @media print {
    .background-card {
      border: none;
    }
  }
```
